/**
 * Consultation form — merged, de-duplicated field config (intake + pre-consult).
 * GENERATED by scripts/gen-consultation-config.js from the verified field map.
 * Single source of truth for the form UI AND the Monday board columns.
 * 94 fields + 2 repeatable groups across 12 sections.
 */
'use strict';

const SECTION_ORDER = [
  "Personal & Contact",
  "Family",
  "Immigration Status",
  "Education",
  "Employment",
  "Language",
  "Your Relationship With TDOT",
  "Service Needed",
  "Service-Specific Questions",
  "Urgency",
  "Final Notes",
  "How You Found Us & Consent"
];
const SERVICE_GROUPS = {
  "Permanent Residence": [
    "Express Entry profile",
    "Express Entry ITA and eAPR",
    "PNP or OINP",
    "Spousal sponsorship",
    "Family sponsorship",
    "Caregiver pathway",
    "Humanitarian and compassionate",
    "PR application review"
  ],
  "Temporary Residence": [
    "Study permit",
    "Work permit",
    "PGWP",
    "BOWP",
    "Visitor visa or TRV",
    "Visitor record",
    "Super Visa",
    "Status extension",
    "Status restoration"
  ],
  "After PR Services": [
    "PR card renewal",
    "PR travel document",
    "Citizenship",
    "Residency obligation review",
    "Name update or document correction"
  ],
  "Employer Services": [
    "LMIA",
    "LMIA exempt work permit",
    "Employer portal submission",
    "Job offer support",
    "Employer compliance support"
  ],
  "Other Support": [
    "Refusal review",
    "ATIP or GCMS notes",
    "Webform",
    "Passport request or VFS support",
    "Document review",
    "Case strategy consultation",
    "Other"
  ]
};
const FBLOCK_SERVICES = {
  "F1": [
    "Express Entry profile",
    "Express Entry ITA and eAPR"
  ],
  "F2": [
    "PNP or OINP"
  ],
  "F3": [
    "Work permit",
    "PGWP",
    "BOWP",
    "Status extension",
    "Status restoration"
  ],
  "F4": [
    "Study permit"
  ],
  "F5": [
    "Visitor visa or TRV",
    "Visitor record",
    "Super Visa"
  ],
  "F6": [
    "Spousal sponsorship",
    "Family sponsorship"
  ],
  "F7": [
    "PR card renewal",
    "PR travel document",
    "Citizenship",
    "Residency obligation review",
    "Name update or document correction"
  ],
  "F8": [
    "LMIA",
    "LMIA exempt work permit",
    "Employer portal submission",
    "Job offer support",
    "Employer compliance support"
  ],
  "F9": [
    "Refusal review"
  ],
  "F10": [
    "ATIP or GCMS notes",
    "Webform",
    "Passport request or VFS support"
  ]
};
const FIELDS = [
  {
    "key": "fullName",
    "label": "Full legal name (as per passport)",
    "section": "Personal & Contact",
    "type": "text",
    "options": [],
    "required": true,
    "mondayType": "text"
  },
  {
    "key": "email",
    "label": "Email address",
    "section": "Personal & Contact",
    "type": "email",
    "options": [],
    "required": true,
    "mondayType": "email"
  },
  {
    "key": "phone",
    "label": "Contact number with country code",
    "section": "Personal & Contact",
    "type": "phone",
    "options": [],
    "required": true,
    "mondayType": "phone"
  },
  {
    "key": "residentialAddress",
    "label": "Current complete residential address",
    "section": "Personal & Contact",
    "type": "textarea",
    "options": [],
    "required": true,
    "mondayType": "long_text"
  },
  {
    "key": "age",
    "label": "Age",
    "section": "Personal & Contact",
    "type": "number",
    "options": [],
    "required": false,
    "mondayType": "numbers"
  },
  {
    "key": "insideCanada",
    "label": "Are you currently inside Canada?",
    "section": "Personal & Contact",
    "type": "radio",
    "options": [
      "Yes",
      "No"
    ],
    "required": true,
    "mondayType": "status"
  },
  {
    "key": "currentCountry",
    "label": "Which country are you currently in?",
    "section": "Personal & Contact",
    "type": "text",
    "options": [],
    "required": true,
    "mondayType": "text",
    "showIf": {
      "field": "insideCanada",
      "in": [
        "No"
      ]
    }
  },
  {
    "key": "entryDate",
    "label": "When did you enter Canada?",
    "section": "Personal & Contact",
    "type": "date",
    "options": [],
    "required": false,
    "mondayType": "date",
    "showIf": {
      "field": "insideCanada",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "entryVisa",
    "label": "What type of visa / permit did you use to enter Canada?",
    "section": "Personal & Contact",
    "type": "dropdown",
    "options": [
      "Visitor visa",
      "Study permit",
      "Work permit",
      "eTA",
      "Other",
      "Not applicable"
    ],
    "required": false,
    "mondayType": "dropdown",
    "showIf": {
      "field": "insideCanada",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "maritalStatus",
    "label": "Marital status",
    "section": "Family",
    "type": "dropdown",
    "options": [
      "Single",
      "Married",
      "Common-law",
      "Separated / Divorced"
    ],
    "required": false,
    "mondayType": "status"
  },
  {
    "key": "hasSpouse",
    "label": "Do you have a spouse or common-law partner?",
    "section": "Family",
    "type": "radio",
    "options": [
      "Yes",
      "No"
    ],
    "required": true,
    "mondayType": "status"
  },
  {
    "key": "spouseAccompanying",
    "label": "Would they accompany you / be included in the application?",
    "section": "Family",
    "type": "radio",
    "options": [
      "Yes",
      "No",
      "Not sure"
    ],
    "required": true,
    "mondayType": "status",
    "showIf": {
      "field": "hasSpouse",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "spouseConsider",
    "label": "Should the spouse's profile also be considered during the consultation?",
    "section": "Family",
    "type": "radio",
    "options": [
      "Yes",
      "No",
      "Not sure"
    ],
    "required": false,
    "mondayType": "status",
    "showIf": {
      "field": "hasSpouse",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "childrenCount",
    "label": "How many dependent children do you have?",
    "section": "Family",
    "type": "number",
    "options": [],
    "required": true,
    "mondayType": "numbers"
  },
  {
    "key": "childrenAccompanying",
    "label": "Would the children accompany you / be included?",
    "section": "Family",
    "type": "dropdown",
    "options": [
      "All",
      "Some",
      "None",
      "Not sure"
    ],
    "required": true,
    "mondayType": "status",
    "showIf": {
      "field": "childrenCount",
      "gt": 0
    }
  },
  {
    "key": "adultChild",
    "label": "Do you have any child over 18 years of age who should be considered?",
    "section": "Family",
    "type": "radio",
    "options": [
      "Yes",
      "No"
    ],
    "required": false,
    "mondayType": "status"
  },
  {
    "key": "relativesInCanada",
    "label": "Do you have any relatives in Canada who are PR or Canadian citizens?",
    "section": "Family",
    "type": "radio",
    "options": [
      "Yes",
      "No"
    ],
    "required": false,
    "mondayType": "status"
  },
  {
    "key": "relativeRelationship",
    "label": "If yes, please mention your relationship",
    "section": "Family",
    "type": "dropdown",
    "options": [
      "Parent",
      "Sibling",
      "Aunt / Uncle",
      "Cousin",
      "Child",
      "Other"
    ],
    "required": false,
    "mondayType": "dropdown",
    "showIf": {
      "field": "relativesInCanada",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "currentStatus",
    "label": "Your current status in the country where you are presently located",
    "section": "Immigration Status",
    "type": "dropdown",
    "options": [
      "Visitor",
      "Student",
      "Worker",
      "Permanent Resident",
      "Citizen",
      "Maintained Status",
      "Out of Status",
      "Not in Canada",
      "Other"
    ],
    "required": true,
    "mondayType": "status"
  },
  {
    "key": "statusExpiry",
    "label": "When does your current status / permit expire? (exact date, not an estimate)",
    "section": "Immigration Status",
    "type": "date",
    "options": [],
    "required": true,
    "mondayType": "date",
    "showIf": {
      "field": "currentStatus",
      "in": [
        "Visitor",
        "Student",
        "Worker"
      ]
    }
  },
  {
    "key": "recentExtension",
    "label": "Have you applied for an extension or change of status recently? (optional)",
    "section": "Immigration Status",
    "type": "radio",
    "options": [
      "Yes",
      "No"
    ],
    "required": false,
    "mondayType": "status"
  },
  {
    "key": "recentExtensionDetails",
    "label": "Application type and submission date (e.g. visitor record submitted on May 1, 2026)",
    "section": "Immigration Status",
    "type": "textarea",
    "options": [],
    "required": false,
    "mondayType": "long_text",
    "showIf": {
      "field": "recentExtension",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "highestEducation",
    "label": "What is your highest completed education after Grade 10?",
    "section": "Education",
    "type": "dropdown",
    "options": [
      "High school",
      "Diploma / Certificate",
      "Bachelor's degree",
      "Post-graduate diploma / certificate",
      "Master's degree",
      "PhD",
      "Trade certificate",
      "Other"
    ],
    "required": false,
    "mondayType": "status"
  },
  {
    "key": "hasTeerExperience",
    "label": "Do you have paid work experience in TEER 0, 1, 2, or 3 in the last 5 years?",
    "section": "Employment",
    "type": "radio",
    "options": [
      "Yes",
      "No",
      "Not sure"
    ],
    "required": false,
    "mondayType": "status"
  },
  {
    "key": "employerRevenueOverMillion",
    "label": "If you are looking for PNP options — did your employer earn more than $1 million in the past year?",
    "section": "Employment",
    "type": "dropdown",
    "options": [
      "Yes",
      "No",
      "Not sure",
      "Not applicable"
    ],
    "required": false,
    "mondayType": "status"
  },
  {
    "key": "englishTest",
    "label": "Do you have an English language test result?",
    "section": "Language",
    "type": "dropdown",
    "options": [
      "Yes",
      "No",
      "Booked but not completed yet"
    ],
    "required": false,
    "mondayType": "status"
  },
  {
    "key": "englishTestType",
    "label": "Which English test?",
    "section": "Language",
    "type": "dropdown",
    "options": [
      "IELTS General",
      "CELPIP General",
      "PTE Core",
      "Other"
    ],
    "required": false,
    "mondayType": "status",
    "showIf": {
      "field": "englishTest",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "engListening",
    "label": "English score — Listening",
    "section": "Language",
    "type": "text",
    "options": [],
    "required": false,
    "mondayType": "text",
    "showIf": {
      "field": "englishTest",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "engReading",
    "label": "English score — Reading",
    "section": "Language",
    "type": "text",
    "options": [],
    "required": false,
    "mondayType": "text",
    "showIf": {
      "field": "englishTest",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "engWriting",
    "label": "English score — Writing",
    "section": "Language",
    "type": "text",
    "options": [],
    "required": false,
    "mondayType": "text",
    "showIf": {
      "field": "englishTest",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "engSpeaking",
    "label": "English score — Speaking",
    "section": "Language",
    "type": "text",
    "options": [],
    "required": false,
    "mondayType": "text",
    "showIf": {
      "field": "englishTest",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "frenchTest",
    "label": "Do you have a French language test result?",
    "section": "Language",
    "type": "dropdown",
    "options": [
      "Yes",
      "No",
      "Booked but not completed yet"
    ],
    "required": false,
    "mondayType": "status"
  },
  {
    "key": "frListening",
    "label": "French score — Listening",
    "section": "Language",
    "type": "text",
    "options": [],
    "required": false,
    "mondayType": "text",
    "showIf": {
      "field": "frenchTest",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "frReading",
    "label": "French score — Reading",
    "section": "Language",
    "type": "text",
    "options": [],
    "required": false,
    "mondayType": "text",
    "showIf": {
      "field": "frenchTest",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "frWriting",
    "label": "French score — Writing",
    "section": "Language",
    "type": "text",
    "options": [],
    "required": false,
    "mondayType": "text",
    "showIf": {
      "field": "frenchTest",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "frSpeaking",
    "label": "French score — Speaking",
    "section": "Language",
    "type": "text",
    "options": [],
    "required": false,
    "mondayType": "text",
    "showIf": {
      "field": "frenchTest",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "relationshipWithTdot",
    "label": "Have you contacted or worked with TDOT Immigration before?",
    "section": "Your Relationship With TDOT",
    "type": "dropdown",
    "options": [
      "New inquiry",
      "Existing client with active application",
      "Previous client with completed or inactive application"
    ],
    "required": true,
    "mondayType": "status"
  },
  {
    "key": "existingFileType",
    "label": "Which service or file type, if known? (e.g. PGWP, Spousal Sponsorship, PR Card, Express Entry)",
    "section": "Your Relationship With TDOT",
    "type": "text",
    "options": [],
    "required": false,
    "mondayType": "text",
    "showIf": {
      "field": "relationshipWithTdot",
      "in": [
        "Existing client with active application",
        "Previous client with completed or inactive application"
      ]
    }
  },
  {
    "key": "serviceRequired",
    "label": "What service or support are you looking for?",
    "section": "Service Needed",
    "type": "dropdown",
    "options": [
      "Express Entry profile",
      "Express Entry ITA and eAPR",
      "PNP or OINP",
      "Spousal sponsorship",
      "Family sponsorship",
      "Caregiver pathway",
      "Humanitarian and compassionate",
      "PR application review",
      "Study permit",
      "Work permit",
      "PGWP",
      "BOWP",
      "Visitor visa or TRV",
      "Visitor record",
      "Super Visa",
      "Status extension",
      "Status restoration",
      "PR card renewal",
      "PR travel document",
      "Citizenship",
      "Residency obligation review",
      "Name update or document correction",
      "LMIA",
      "LMIA exempt work permit",
      "Employer portal submission",
      "Job offer support",
      "Employer compliance support",
      "Refusal review",
      "ATIP or GCMS notes",
      "Webform",
      "Passport request or VFS support",
      "Document review",
      "Case strategy consultation",
      "Other"
    ],
    "required": true,
    "mondayType": "dropdown"
  },
  {
    "key": "situationDescription",
    "label": "Please briefly explain your inquiry or goal",
    "section": "Service Needed",
    "type": "textarea",
    "options": [],
    "required": true,
    "mondayType": "long_text"
  },
  {
    "key": "whatDoYouWant",
    "label": "What would you like to do?",
    "section": "Service Needed",
    "type": "dropdown",
    "options": [
      "Book consultation",
      "Start new application",
      "Request quote",
      "Existing file update",
      "General information"
    ],
    "required": true,
    "mondayType": "status"
  },
  {
    "key": "f1_hasProfile",
    "label": "Do you have a valid Express Entry profile?",
    "section": "Service-Specific Questions",
    "type": "radio",
    "options": [
      "Yes",
      "No"
    ],
    "required": false,
    "mondayType": "status",
    "block": "F1"
  },
  {
    "key": "f1_crsScore",
    "label": "What is your CRS score?",
    "section": "Service-Specific Questions",
    "type": "number",
    "options": [],
    "required": false,
    "mondayType": "numbers",
    "block": "F1"
  },
  {
    "key": "f1_hasIta",
    "label": "Have you received an ITA?",
    "section": "Service-Specific Questions",
    "type": "radio",
    "options": [
      "Yes",
      "No"
    ],
    "required": false,
    "mondayType": "status",
    "block": "F1"
  },
  {
    "key": "f1_itaDeadline",
    "label": "ITA deadline",
    "section": "Service-Specific Questions",
    "type": "date",
    "options": [],
    "required": false,
    "mondayType": "date",
    "block": "F1",
    "showIf": {
      "field": "f1_hasIta",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "f1_program",
    "label": "Which program or draw invited you, if known?",
    "section": "Service-Specific Questions",
    "type": "text",
    "options": [],
    "required": false,
    "mondayType": "text",
    "block": "F1",
    "showIf": {
      "field": "f1_hasIta",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "f2_hasNomination",
    "label": "Have you received a NOI, nomination, or invitation?",
    "section": "Service-Specific Questions",
    "type": "radio",
    "options": [
      "Yes",
      "No"
    ],
    "required": false,
    "mondayType": "status",
    "block": "F2"
  },
  {
    "key": "f2_deadline",
    "label": "Deadline, if any",
    "section": "Service-Specific Questions",
    "type": "date",
    "options": [],
    "required": false,
    "mondayType": "date",
    "block": "F2"
  },
  {
    "key": "f2_province",
    "label": "Which province?",
    "section": "Service-Specific Questions",
    "type": "text",
    "options": [],
    "required": false,
    "mondayType": "text",
    "block": "F2"
  },
  {
    "key": "f2_employerSupport",
    "label": "Are you applying with employer support?",
    "section": "Service-Specific Questions",
    "type": "radio",
    "options": [
      "Yes",
      "No"
    ],
    "required": false,
    "mondayType": "status",
    "block": "F2"
  },
  {
    "key": "f3_permitType",
    "label": "What type of work permit do you currently hold?",
    "section": "Service-Specific Questions",
    "type": "text",
    "options": [],
    "required": false,
    "mondayType": "text",
    "block": "F3"
  },
  {
    "key": "f3_expiry",
    "label": "What is the expiry date?",
    "section": "Service-Specific Questions",
    "type": "date",
    "options": [],
    "required": false,
    "mondayType": "date",
    "block": "F3"
  },
  {
    "key": "f3_prSubmitted",
    "label": "Have you submitted a PR application or received an AOR?",
    "section": "Service-Specific Questions",
    "type": "radio",
    "options": [
      "Yes",
      "No"
    ],
    "required": false,
    "mondayType": "status",
    "block": "F3"
  },
  {
    "key": "f3_employerDocs",
    "label": "Do you have employer documents?",
    "section": "Service-Specific Questions",
    "type": "radio",
    "options": [
      "Yes",
      "No"
    ],
    "required": false,
    "mondayType": "status",
    "block": "F3"
  },
  {
    "key": "f4_intake",
    "label": "Which intake are you targeting?",
    "section": "Service-Specific Questions",
    "type": "text",
    "options": [],
    "required": false,
    "mondayType": "text",
    "block": "F4"
  },
  {
    "key": "f4_admission",
    "label": "Have you received admission?",
    "section": "Service-Specific Questions",
    "type": "radio",
    "options": [
      "Yes",
      "No"
    ],
    "required": false,
    "mondayType": "status",
    "block": "F4"
  },
  {
    "key": "f4_need",
    "label": "Do you need application filing or document review?",
    "section": "Service-Specific Questions",
    "type": "dropdown",
    "options": [
      "Application filing",
      "Document review",
      "Both"
    ],
    "required": false,
    "mondayType": "status",
    "block": "F4"
  },
  {
    "key": "f4_deadline",
    "label": "School deadline, if any",
    "section": "Service-Specific Questions",
    "type": "date",
    "options": [],
    "required": false,
    "mondayType": "date",
    "block": "F4"
  },
  {
    "key": "f5_location",
    "label": "Are you inside or outside Canada?",
    "section": "Service-Specific Questions",
    "type": "dropdown",
    "options": [
      "Inside Canada",
      "Outside Canada"
    ],
    "required": false,
    "mondayType": "status",
    "block": "F5"
  },
  {
    "key": "f5_purpose",
    "label": "What is the purpose of travel or stay extension?",
    "section": "Service-Specific Questions",
    "type": "textarea",
    "options": [],
    "required": false,
    "mondayType": "long_text",
    "block": "F5"
  },
  {
    "key": "f5_priorRefusal",
    "label": "Have you had a refusal before? (any refusal, even years ago)",
    "section": "Service-Specific Questions",
    "type": "radio",
    "options": [
      "Yes",
      "No"
    ],
    "required": false,
    "mondayType": "status",
    "block": "F5"
  },
  {
    "key": "f6_whoSponsors",
    "label": "Who is sponsoring whom?",
    "section": "Service-Specific Questions",
    "type": "text",
    "options": [],
    "required": false,
    "mondayType": "text",
    "block": "F6"
  },
  {
    "key": "f6_sponsorStatus",
    "label": "Is the sponsor a citizen or permanent resident?",
    "section": "Service-Specific Questions",
    "type": "dropdown",
    "options": [
      "Citizen",
      "Permanent resident",
      "Not sure"
    ],
    "required": false,
    "mondayType": "status",
    "block": "F6"
  },
  {
    "key": "f6_applicantLocation",
    "label": "Is the applicant inside or outside Canada?",
    "section": "Service-Specific Questions",
    "type": "dropdown",
    "options": [
      "Inside Canada",
      "Outside Canada"
    ],
    "required": false,
    "mondayType": "status",
    "block": "F6"
  },
  {
    "key": "f6_concerns",
    "label": "Any previous refusal or marriage-history concern?",
    "section": "Service-Specific Questions",
    "type": "text",
    "options": [],
    "required": false,
    "mondayType": "text",
    "block": "F6"
  },
  {
    "key": "f7_serviceNeeded",
    "label": "Do you need PR card renewal, PRTD, citizenship, or residency obligation review?",
    "section": "Service-Specific Questions",
    "type": "dropdown",
    "options": [
      "PR card renewal",
      "PR travel document (PRTD)",
      "Citizenship",
      "Residency obligation review"
    ],
    "required": false,
    "mondayType": "status",
    "block": "F7"
  },
  {
    "key": "f7_prDate",
    "label": "When did you become a permanent resident?",
    "section": "Service-Specific Questions",
    "type": "date",
    "options": [],
    "required": false,
    "mondayType": "date",
    "block": "F7"
  },
  {
    "key": "f7_insideCanada",
    "label": "Are you inside or outside Canada?",
    "section": "Service-Specific Questions",
    "type": "dropdown",
    "options": [
      "Inside Canada",
      "Outside Canada"
    ],
    "required": false,
    "mondayType": "status",
    "block": "F7"
  },
  {
    "key": "f8_role",
    "label": "Are you the employer or the employee?",
    "section": "Service-Specific Questions",
    "type": "dropdown",
    "options": [
      "Employer",
      "Employee"
    ],
    "required": false,
    "mondayType": "status",
    "block": "F8"
  },
  {
    "key": "f8_jobTitle",
    "label": "What is the job title?",
    "section": "Service-Specific Questions",
    "type": "text",
    "options": [],
    "required": false,
    "mondayType": "text",
    "block": "F8"
  },
  {
    "key": "f8_supportType",
    "label": "Is this LMIA, employer portal, OINP employer, or compliance support?",
    "section": "Service-Specific Questions",
    "type": "dropdown",
    "options": [
      "LMIA",
      "Employer portal",
      "OINP employer",
      "Compliance support"
    ],
    "required": false,
    "mondayType": "status",
    "block": "F8"
  },
  {
    "key": "f9_refusalType",
    "label": "What application was refused?",
    "section": "Service-Specific Questions",
    "type": "dropdown",
    "options": [
      "Visitor visa",
      "Study permit",
      "Work permit",
      "Spousal sponsorship",
      "PR application",
      "Express Entry",
      "PNP",
      "Refugee or H and C",
      "Other"
    ],
    "required": false,
    "mondayType": "status",
    "block": "F9"
  },
  {
    "key": "f9_refusalDate",
    "label": "Date of the refusal (even if it was a long time ago)",
    "section": "Service-Specific Questions",
    "type": "date",
    "options": [],
    "required": false,
    "mondayType": "date",
    "block": "F9"
  },
  {
    "key": "f9_deadline",
    "label": "Any upcoming deadline to reapply or respond?",
    "section": "Service-Specific Questions",
    "type": "date",
    "options": [],
    "required": false,
    "mondayType": "date",
    "block": "F9"
  },
  {
    "key": "f10_need",
    "label": "What document or update do you need?",
    "section": "Service-Specific Questions",
    "type": "text",
    "options": [],
    "required": false,
    "mondayType": "text",
    "block": "F10"
  },
  {
    "key": "f10_deadline",
    "label": "Is there a deadline?",
    "section": "Service-Specific Questions",
    "type": "date",
    "options": [],
    "required": false,
    "mondayType": "date",
    "block": "F10"
  },
  {
    "key": "urgentDeadline",
    "label": "Do you have any urgent deadline connected to your inquiry?",
    "section": "Urgency",
    "type": "radio",
    "options": [
      "Yes",
      "No"
    ],
    "required": true,
    "mondayType": "status"
  },
  {
    "key": "deadlineDate",
    "label": "Deadline date",
    "section": "Urgency",
    "type": "date",
    "options": [],
    "required": true,
    "mondayType": "date",
    "showIf": {
      "field": "urgentDeadline",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "deadlineReason",
    "label": "Reason for the deadline",
    "section": "Urgency",
    "type": "dropdown",
    "options": [
      "ITA deadline",
      "Passport request deadline",
      "Restoration deadline",
      "Status expiry",
      "CBSA or removal matter",
      "Hearing or appointment",
      "PNP deadline",
      "Employer deadline",
      "School deadline",
      "Other"
    ],
    "required": true,
    "mondayType": "status",
    "showIf": {
      "field": "urgentDeadline",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "removalOrder",
    "label": "Are you currently subject to a removal, departure, exclusion, or deportation order, or any enforcement action?",
    "section": "Urgency",
    "type": "radio",
    "options": [
      "Yes",
      "No",
      "Not sure"
    ],
    "required": true,
    "mondayType": "status"
  },
  {
    "key": "enforcementLetter",
    "label": "Have you received any letter, notice, call, or communication from CBSA, IRCC, or law enforcement asking you to attend, leave, or respond?",
    "section": "Urgency",
    "type": "radio",
    "options": [
      "Yes",
      "No",
      "Not sure"
    ],
    "required": true,
    "mondayType": "status"
  },
  {
    "key": "enforcementDetails",
    "label": "Details — what the letter says, who it is from, any dates",
    "section": "Urgency",
    "type": "textarea",
    "options": [],
    "required": false,
    "mondayType": "long_text",
    "showIf": {
      "anyOf": [
        {
          "field": "removalOrder",
          "in": [
            "Yes"
          ]
        },
        {
          "field": "enforcementLetter",
          "in": [
            "Yes"
          ]
        }
      ]
    }
  },
  {
    "key": "restorationPeriod",
    "label": "Are you currently within a restoration period?",
    "section": "Urgency",
    "type": "radio",
    "options": [
      "Yes",
      "No"
    ],
    "required": true,
    "mondayType": "status"
  },
  {
    "key": "restorationDeadline",
    "label": "Restoration deadline (exact date if known)",
    "section": "Urgency",
    "type": "date",
    "options": [],
    "required": false,
    "mondayType": "date",
    "showIf": {
      "field": "restorationPeriod",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "recentRefusal",
    "label": "Do you have any recent refusal?",
    "section": "Urgency",
    "type": "radio",
    "options": [
      "Yes",
      "No"
    ],
    "required": true,
    "mondayType": "status"
  },
  {
    "key": "refusalType",
    "label": "What was refused?",
    "section": "Urgency",
    "type": "dropdown",
    "options": [
      "Visitor visa",
      "Study permit",
      "Work permit",
      "Spousal sponsorship",
      "PR application",
      "Express Entry",
      "PNP",
      "Refugee or H and C",
      "Other"
    ],
    "required": true,
    "mondayType": "status",
    "showIf": {
      "field": "recentRefusal",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "refusalDate",
    "label": "Date of most recent refusal",
    "section": "Urgency",
    "type": "date",
    "options": [],
    "required": true,
    "mondayType": "date",
    "showIf": {
      "field": "recentRefusal",
      "in": [
        "Yes"
      ]
    }
  },
  {
    "key": "finalNote",
    "label": "Is there anything important you want the consultant to know before the consultation? (optional)",
    "section": "Final Notes",
    "type": "textarea",
    "options": [],
    "required": false,
    "mondayType": "long_text"
  },
  {
    "key": "howHeard",
    "label": "How did you hear about TDOT Immigration?",
    "section": "How You Found Us & Consent",
    "type": "dropdown",
    "options": [
      "Existing client",
      "Referral",
      "Social media",
      "Google",
      "Website",
      "Walk in",
      "Event"
    ],
    "required": true,
    "mondayType": "status"
  },
  {
    "key": "referredBy",
    "label": "Who referred you?",
    "section": "How You Found Us & Consent",
    "type": "text",
    "options": [],
    "required": false,
    "mondayType": "text"
  },
  {
    "key": "consentContact",
    "label": "I consent to TDOT Immigration contacting me by phone, WhatsApp, email, or message regarding my inquiry.",
    "section": "How You Found Us & Consent",
    "type": "checkbox",
    "options": [],
    "required": true,
    "mondayType": "status"
  },
  {
    "key": "consentAccuracy",
    "label": "I confirm that the information provided in this form is true and accurate to the best of my knowledge.",
    "section": "How You Found Us & Consent",
    "type": "checkbox",
    "options": [],
    "required": true,
    "mondayType": "status"
  },
  {
    "key": "consentDisclaimer",
    "label": "I understand that submitting this form does not guarantee eligibility, approval, or representation by TDOT Immigration, and that case-specific advice may require a paid consultation.",
    "section": "How You Found Us & Consent",
    "type": "checkbox",
    "options": [],
    "required": true,
    "mondayType": "status"
  },
  {
    "key": "consentStorage",
    "label": "I consent to TDOT Immigration storing this information for intake, follow-up, and service assessment purposes.",
    "section": "How You Found Us & Consent",
    "type": "checkbox",
    "options": [],
    "required": true,
    "mondayType": "status"
  }
];
const GROUPS = [
  {
    "group": "education",
    "section": "Education",
    "sub": [
      {
        "key": "school",
        "label": "School / college / university name",
        "type": "text",
        "options": [],
        "mondayType": "long_text"
      },
      {
        "key": "program",
        "label": "Program / field name",
        "type": "text",
        "options": [],
        "mondayType": "long_text"
      },
      {
        "key": "location",
        "label": "City and country of study",
        "type": "text",
        "options": [],
        "mondayType": "long_text"
      },
      {
        "key": "start",
        "label": "Start (MM/YYYY)",
        "type": "text",
        "options": [],
        "mondayType": "text"
      },
      {
        "key": "end",
        "label": "End (MM/YYYY)",
        "type": "text",
        "options": [],
        "mondayType": "text"
      },
      {
        "key": "completed",
        "label": "Completed?",
        "type": "dropdown",
        "options": [
          "Yes",
          "No, currently studying",
          "No, not completed"
        ],
        "mondayType": "status"
      }
    ]
  },
  {
    "group": "employment",
    "section": "Employment",
    "sub": [
      {
        "key": "title",
        "label": "Job title",
        "type": "text",
        "options": [],
        "mondayType": "long_text"
      },
      {
        "key": "company",
        "label": "Company name",
        "type": "text",
        "options": [],
        "mondayType": "long_text"
      },
      {
        "key": "country",
        "label": "Country of employment",
        "type": "text",
        "options": [],
        "mondayType": "text"
      },
      {
        "key": "start",
        "label": "Start (MM/YYYY)",
        "type": "text",
        "options": [],
        "mondayType": "text"
      },
      {
        "key": "end",
        "label": "End (MM/YYYY)",
        "type": "text",
        "options": [],
        "mondayType": "text"
      },
      {
        "key": "type",
        "label": "Full-time / part-time",
        "type": "dropdown",
        "options": [
          "Full-time",
          "Part-time"
        ],
        "mondayType": "status"
      },
      {
        "key": "hours",
        "label": "Approx. hours / week",
        "type": "number",
        "options": [],
        "mondayType": "numbers"
      },
      {
        "key": "duties",
        "label": "Briefly describe your main duties (plain words — helps us find your NOC code)",
        "type": "textarea",
        "options": [],
        "mondayType": "long_text"
      }
    ]
  }
];

module.exports = { SECTION_ORDER, SERVICE_GROUPS, FBLOCK_SERVICES, FIELDS, GROUPS };
