/**
 * Questionnaire Pre-fill Map
 *
 * Pure, data-first mapping from the client data we ALREADY have (intake +
 * pre-consult submissions + Lead Board columns + Family Members rows) onto the
 * HTML questionnaire's answer fields.
 *
 * How the match works (see htmlQuestionnaireService prefillMemberSection):
 *   The client form re-hydrates by matching each saved field to a DOM field by
 *   `key` first, then case-insensitively by `label` (positional occurrence).
 *   So we seed by the questionnaire's VISIBLE LABEL text — we do NOT try to
 *   reproduce the brittle DOM-slug key. A seeded entry whose label doesn't
 *   exist in a given form is simply ignored, so the same map is form-agnostic.
 *
 * Label-collision caution (learned from the real forms):
 *   The applicant's surname/given anchor ONLY on "Family Name (Surname)". The
 *   bare "Family Name" / "Given Name" labels also appear for the *other-name*
 *   and *spouse* blocks; because matching fills the FIRST occurrence, "Given
 *   Name" is safe (the applicant's is first) but bare "Family Name" is NOT, so
 *   it is never emitted for the applicant.
 *
 * This module is PURE (no I/O) so it is fully unit-testable.
 */

'use strict';

/** Split a full name into { surname, given }. Best-effort: last token = surname. */
function splitName(full) {
  const s = String(full || '').trim().replace(/\s+/g, ' ');
  if (!s) return { surname: '', given: '' };
  const parts = s.split(' ');
  if (parts.length === 1) return { surname: parts[0], given: '' };
  return { surname: parts[parts.length - 1], given: parts.slice(0, -1).join(' ') };
}

/**
 * Names auto-generated by familyCompositionService for members the client never
 * named individually (e.g. "Spouse (from intake)", "Child 1 (from intake)").
 * We must never seed these as a real surname/given.
 */
const PLACEHOLDER_NAME_RE = /\(from intake\)|^\s*(spouse|dependent child|child\s*\d*)\s*$/i;
function isRealName(name) {
  const n = String(name || '').trim();
  return !!n && !PLACEHOLDER_NAME_RE.test(n);
}

/** First non-empty, trimmed value among the given candidates. */
function firstNonEmpty(...vals) {
  for (const v of vals) {
    if (v != null && String(v).trim() !== '') return String(v).trim();
  }
  return '';
}

const YES = 'Yes';
const NO  = 'No';

/** Normalise a truthy/falsey answer to 'Yes' / 'No' / '' (unknown). */
function yesNo(v) {
  const s = String(v == null ? '' : v).trim().toLowerCase();
  if (['yes', 'true', 'y', '1'].includes(s)) return YES;
  if (['no', 'false', 'n', '0'].includes(s)) return NO;
  return '';
}

/**
 * Pull the first non-empty value for one of `keys` across the merged sources,
 * in precedence order: intake archive → pre-consult archive → lead columns.
 */
function pick(ctx, ...keys) {
  const sources = [ctx.intake || {}, ctx.preConsult || {}, ctx.lead || {}];
  for (const key of keys) {
    for (const src of sources) {
      const v = src[key];
      if (v == null || typeof v === 'object') continue;  // ignore nested rows (education/employment arrays)
      if (String(v).trim() !== '') return String(v).trim();
    }
  }
  return '';
}

// ── Derived / transformed values ─────────────────────────────────────────────

/** Current residence country: inside Canada ⇒ "Canada", else the stated country. */
function residenceCountry(ctx) {
  const inside = firstNonEmpty(ctx.lead && ctx.lead.insideCanada, pick(ctx, 'insideCanada')).toLowerCase();
  if (inside === 'yes') return 'Canada';
  return pick(ctx, 'currentCountry', 'country');
}

/** Accompanying-spouse answer: explicit accompaniment first, else spouse presence. */
function accompanyingSpouse(ctx) {
  const acc = pick(ctx, 'spouseAccompanying');
  if (acc) return yesNo(acc) || acc;
  const has = pick(ctx, 'hasSpouse');
  return has ? yesNo(has) : '';
}

/** Dependent-children answer (Yes/No radio — F1). */
function dependentChildren(ctx) {
  const n = pick(ctx, 'childrenCount');
  if (n === '') return '';
  return Number(n) > 0 ? YES : NO;
}

/** Dependent-children answer for the free-text "…How Many?" variant (F6 et al.). */
function dependentChildrenText(ctx) {
  const n = pick(ctx, 'childrenCount');
  if (n === '') return '';
  return Number(n) > 0 ? `Yes - ${n}` : NO;
}

/**
 * Normalise a marital value onto what the questionnaire selects actually offer.
 * The source enum has one atomic "Separated / Divorced" token but the forms
 * split them, so pick the conservative "Separated" (client confirms via banner).
 */
function normalizeMarital(v) {
  const s = String(v || '').trim();
  if (!s) return '';
  if (/separated\s*\/\s*divorced/i.test(s)) return 'Separated';
  return s;
}

/**
 * Convert a stored ISO date (YYYY-MM-DD, e.g. a Monday date column) to the
 * questionnaire's DD/MM/YYYY text format. Passes anything else through.
 */
function isoToDdmmyyyy(v) {
  const s = String(v || '').trim();
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(s);
  return m ? `${m[3]}/${m[2]}/${m[1]}` : s;
}

/**
 * Only surface refusal detail when a refusal was actually reported.
 *   • recentRefusal = Yes  → surface
 *   • recentRefusal = No   → suppress (even if a stale date lingers)
 *   • unset                → infer from the presence of a refusal date
 *                            (covers F9 / Lost-PR-Card, which sets a date directly)
 */
function hadRefusal(ctx) {
  const flag = yesNo(pick(ctx, 'recentRefusal'));
  if (flag === YES) return true;
  if (flag === NO)  return false;
  return !!pick(ctx, 'refusalDate', 'f9_refusalDate');
}
function refusalDate(ctx) { return hadRefusal(ctx) ? pick(ctx, 'refusalDate', 'f9_refusalDate') : ''; }
function refusalType(ctx) { return hadRefusal(ctx) ? pick(ctx, 'refusalType', 'f9_refusalType') : ''; }

// ── Rule tables ──────────────────────────────────────────────────────────────
// Each rule: { labels: [exact questionnaire label(s)], value: (arg) => string }.
// A rule contributes an entry per label only when its value is non-empty.

const PRIMARY_RULES = [
  { labels: ['Family Name (Surname)'],              value: (c) => splitName(pick(c, 'fullName')).surname },
  { labels: ['Given Name'],                          value: (c) => splitName(pick(c, 'fullName')).given },
  { labels: ['Email Address'],                       value: (c) => pick(c, 'email') },
  { labels: ['Phone Number', 'Mobile Number'],       value: (c) => pick(c, 'phone') },
  { labels: ['Current Residential Address', 'Residential Address'], value: (c) => pick(c, 'residentialAddress') },
  { labels: ['Current Residence Country'],           value: residenceCountry },
  // Bare label = free-text forms (F7/F8/F11/…); parenthetical = the <select> forms (F2/F3/F5/F6, the PNP/EE family).
  { labels: ['Status in Current Country', 'Status in Current Country (Visitor, Student, Worker, Citizen)'], value: (c) => pick(c, 'currentStatus') },
  { labels: ['Current Marital Status'],              value: (c) => normalizeMarital(pick(c, 'maritalStatus', 'pc_marital')) },
  { labels: ['Do you have an accompanying spouse?', 'Accompanying spouse?'], value: accompanyingSpouse },
  { labels: ['Do you have dependent children?'],     value: dependentChildren },
  { labels: ['Do you have dependent children? How Many?'], value: dependentChildrenText },
  { labels: ['Date of Refusal'],                     value: refusalDate },
  { labels: ['Visa Type'],                           value: refusalType },
  { labels: ["Spouse's Family Name"],                value: (c) => (c.spouse && isRealName(c.spouse.name)) ? splitName(c.spouse.name).surname : '' },
  { labels: ["Spouse's Given Name"],                 value: (c) => (c.spouse && isRealName(c.spouse.name)) ? splitName(c.spouse.name).given : '' },
  { labels: ["Spouse's Date of Birth"],              value: (c) => (c.spouse && c.spouse.dateOfBirth) ? isoToDdmmyyyy(c.spouse.dateOfBirth) : '' },
];

// Per-member forms (spouse / child-N). Intake holds almost no per-member
// biographic detail, so this is thin today — the name (only when the consultant
// set a real one) plus any DOB/status/residence IF the Family Members board is
// later wired to carry them (currently blank, so those rules emit nothing).
const MEMBER_RULES = [
  { labels: ['Family Name (Surname)'],               value: (m) => isRealName(m.name) ? splitName(m.name).surname : '' },
  { labels: ['Given Name'],                          value: (m) => isRealName(m.name) ? splitName(m.name).given : '' },
  { labels: ['Date of Birth'],                       value: (m) => isoToDdmmyyyy(m.dateOfBirth || '') },
  { labels: ['Status in Current Country', 'Status in Current Country (Visitor, Student, Worker, Citizen)'], value: (m) => m.currentStatus || '' },
  { labels: ['Current Residence Country'],           value: (m) => m.countryOfResidence || '' },
];

/**
 * Apply a rule table to an argument, returning [{ label, value }].
 * A label is never emitted twice (first rule to claim it wins).
 */
function applyRules(rules, arg) {
  const out = [];
  const seen = new Set();
  for (const rule of rules) {
    let val;
    try { val = rule.value(arg); } catch { val = ''; }
    if (val == null || String(val).trim() === '') continue;
    val = String(val).trim();
    for (const label of rule.labels) {
      const k = label.trim().toLowerCase();
      if (seen.has(k)) continue;
      seen.add(k);
      out.push({ label, value: val });
    }
  }
  return out;
}

/**
 * Build the principal-applicant pre-fill pairs.
 * @param {{ intake?, preConsult?, lead?, spouse?: {name} }} ctx
 * @returns {Array<{label:string, value:string}>}
 */
function buildPrimaryFields(ctx) {
  return applyRules(PRIMARY_RULES, ctx || {});
}

/**
 * Build a family member's pre-fill pairs.
 * @param {{ name?, dateOfBirth?, currentStatus?, countryOfResidence? }} member
 * @returns {Array<{label:string, value:string}>}
 */
function buildMemberFields(member) {
  return applyRules(MEMBER_RULES, member || {});
}

module.exports = {
  splitName,
  isRealName,
  yesNo,
  buildPrimaryFields,
  buildMemberFields,
  _internal: { PRIMARY_RULES, MEMBER_RULES, residenceCountry, accompanyingSpouse, dependentChildren, refusalDate, pick },
};
